In [19]:
# os - interact with operating system, crate files, directories
import os
import pandas as pd
import numpy as np

In [20]:
# visualization and plottind
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
# preprocessing helpers (and ml)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.impute import SimpleImputer

In [22]:
RANDOM_STATE=42
np.random.seed(RANDOM_STATE)

print("Imported libraries. currently woking in: ", os.getcwd())

Imported libraries. currently woking in:  C:\Users\HP\anaconda_projects\kNN_comparative_study

In [23]:
# loading data
DATA_PATH="Mental_Health_and_Social_Media_Balance_Dataset.csv"

if not os.path.exists(DATA_PATH):
    raise FileNotFoundEror(f"File not found at {DATA_PATH}. Modify path, or place file in cwd.")

df=pd.read_csv(DATA_PATH)
print("Dataset loaded. Size: ", df.shape)

Dataset loaded. Size:  (500, 10)

In [24]:
display(df.head(10))

,User_ID,Age,Gender,Daily_Screen_Time(hrs),Sleep_Quality(1-10),Stress_Level(1-10),Days_Without_Social_Media,Exercise_Frequency(week),Social_Media_Platform,Happiness_Index(1-10)
0,U001,44,Male,3.1,7.0,6.0,2.0,5.0,Facebook,10.0
1,U002,30,Other,5.1,7.0,8.0,5.0,3.0,LinkedIn,10.0
2,U003,23,Other,7.4,6.0,7.0,1.0,3.0,YouTube,6.0
3,U004,36,Female,5.7,7.0,8.0,1.0,1.0,TikTok,8.0
4,U005,34,Female,7.0,4.0,7.0,5.0,1.0,X (Twitter),8.0
5,U006,38,Male,6.6,5.0,7.0,4.0,3.0,LinkedIn,8.0
6,U007,26,Female,7.8,4.0,8.0,2.0,0.0,TikTok,7.0
7,U008,26,Female,7.4,5.0,6.0,1.0,4.0,Instagram,7.0
8,U009,39,Male,4.7,7.0,7.0,6.0,1.0,YouTube,9.0
9,U010,39,Female,6.6,6.0,8.0,0.0,2.0,Facebook,7.0

In [25]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    500 non-null    object
 1   Age                        500 non-null    int64
 2   Gender                     500 non-null    object
 3   Daily_Screen_Time(hrs)     500 non-null    float64
 4   Sleep_Quality(1-10)        500 non-null    float64
 5   Stress_Level(1-10)         500 non-null    float64
 6   Days_Without_Social_Media  500 non-null    float64
 7   Exercise_Frequency(week)   500 non-null    float64
 8   Social_Media_Platform      500 non-null    object
 9   Happiness_Index(1-10)      500 non-null    float64
dtypes: float64(6), int64(1), object(3)
memory usage: 39.2+ KB

None

In [26]:
print(f"statistics for numerical columns")
display(df.describe(include='number').T)

statistics for numerical columns

,count,mean,std,min,25%,50%,75%,max
Age,500.0,32.988,9.960637,16.0,24.0,34.0,41.0,49.0
Daily_Screen_Time(hrs),500.0,5.530,1.734877,1.0,4.3,5.6,6.7,10.8
Sleep_Quality(1-10),500.0,6.304,1.529792,2.0,5.0,6.0,7.0,10.0
Stress_Level(1-10),500.0,6.618,1.542996,2.0,6.0,7.0,8.0,10.0
Days_Without_Social_Media,500.0,3.134,1.858751,0.0,2.0,3.0,5.0,9.0
Exercise_Frequency(week),500.0,2.448,1.428067,0.0,1.0,2.0,3.0,7.0
Happiness_Index(1-10),500.0,8.376,1.524228,4.0,7.0,9.0,10.0,10.0

In [27]:
# what columns are missing 
display(df.isnull().sum().sort_values(ascending=False).head(30))

User_ID                      0
Age                          0
Gender                       0
Daily_Screen_Time(hrs)       0
Sleep_Quality(1-10)          0
Stress_Level(1-10)           0
Days_Without_Social_Media    0
Exercise_Frequency(week)     0
Social_Media_Platform        0
Happiness_Index(1-10)        0
dtype: int64

In [28]:
# duplicates check and overview 
print("how many duplicates:" , df.duplicated().sum())

print("column types:")
display(df.dtypes.value_counts())
display(df.select_dtypes(include=['object']).columns.tolist()[:50])

how many duplicates: 0
column types:

float64    6
object     3
int64      1
Name: count, dtype: int64

['User_ID', 'Gender', 'Social_Media_Platform']

In [29]:
# pre-processing:
# elliminate user id, convert genders and social media platforms in numerical values, 
# (one-hot encoding for socials)
# Happiness_Index - target

from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

# drop ID's
df=df.drop('User_ID', axis=1)

#  gender -> numeical
le_gender=LabelEncoder()
df['Gender']=le_gender.fit_transform(df['Gender']) # (Male=1, Female=0, Other=2)

# One-hot for socials
df=pd.get_dummies(df,columns=['Social_Media_Platform'],drop_first=True)

# define x=features and y=target
X=df.drop('Happiness_Index(1-10)',axis=1)
Y=df['Happiness_Index(1-10)']

In [30]:
# scale numericals
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

In [31]:
# dividing into training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    X_scaled, Y, test_size=0.2, random_state=42
) # X dependents - they are all numpy arrays now, Y - series

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (400, 12)
Test shape: (100, 12)

In [32]:
# display(df.head(10))

In [36]:
# see the progress
display(pd.DataFrame(X_train, columns=X.columns).head())

display(pd.DataFrame(X_test, columns=X.columns).head())

display(Y_train.head())

display(Y_test.head())

,Age,Gender,Daily_Screen_Time(hrs),Sleep_Quality(1-10),Stress_Level(1-10),Days_Without_Social_Media,Exercise_Frequency(week),Social_Media_Platform_Instagram,Social_Media_Platform_LinkedIn,Social_Media_Platform_TikTok,Social_Media_Platform_X (Twitter),Social_Media_Platform_YouTube
0,1.508642,0.712619,-0.132707,-0.853257,-1.049659,-0.610698,0.386924,-0.416784,2.17879,-0.484322,-0.462160,-0.420084
1,-0.903256,0.712619,-0.767393,1.109758,0.247818,1.004906,0.386924,-0.416784,-0.45897,-0.484322,2.163751,-0.420084
2,0.403189,0.712619,0.905869,-0.198919,-0.400921,1.004906,1.087872,-0.416784,-0.45897,2.064742,-0.462160,-0.420084
3,0.403189,0.712619,-0.132707,0.455419,0.247818,1.004906,-1.014974,-0.416784,-0.45897,2.064742,-0.462160,-0.420084
4,-1.305239,0.712619,1.078965,-1.507595,1.545296,0.466371,-0.314025,2.399324,-0.45897,-0.484322,-0.462160,-0.420084

,Age,Gender,Daily_Screen_Time(hrs),Sleep_Quality(1-10),Stress_Level(1-10),Days_Without_Social_Media,Exercise_Frequency(week),Social_Media_Platform_Instagram,Social_Media_Platform_LinkedIn,Social_Media_Platform_TikTok,Social_Media_Platform_X (Twitter),Social_Media_Platform_YouTube
0,0.604180,-1.017039,0.617376,-0.198919,0.247818,-0.072164,-1.014974,2.399324,-0.45897,-0.484322,-0.46216,-0.420084
1,-0.702264,-1.017039,-0.421200,-0.198919,-0.400921,-1.149233,1.087872,-0.416784,2.17879,-0.484322,-0.46216,-0.420084
2,-1.606726,0.712619,0.155786,-0.198919,0.247818,-1.149233,1.788821,-0.416784,-0.45897,2.064742,-0.46216,-0.420084
3,-1.405734,-1.017039,-0.190406,0.455419,-1.049659,0.466371,1.087872,-0.416784,2.17879,-0.484322,-0.46216,-0.420084
4,-1.405734,0.712619,0.963568,-0.853257,-0.400921,-1.149233,-1.715922,-0.416784,2.17879,-0.484322,-0.46216,-0.420084

249     8.0
433     7.0
19     10.0
322     8.0
332     6.0
Name: Happiness_Index(1-10), dtype: float64

361     7.0
73      8.0
374     9.0
155    10.0
104     9.0
Name: Happiness_Index(1-10), dtype: float64

In [37]:
X_train = pd.DataFrame(X_train, columns=X.columns)
X_test = pd.DataFrame(X_test, columns=X.columns)


X_train.to_csv("X_train_preprocessed.csv", index=False)
X_test.to_csv("X_test_preprocessed.csv", index=False)
pd.Series(Y_train, name='target').to_csv("Y_train.csv", index=False)
pd.Series(Y_test, name='target').to_csv("Y_test.csv", index=False)
print("Fișiere preprocesate salvate: X_train_preprocessed.csv, X_test_preprocessed.csv, Y_train.csv, Y_test.csv")

Fișiere preprocesate salvate: X_train_preprocessed.csv, X_test_preprocessed.csv, Y_train.csv, Y_test.csv